site_name: Jornada do Estudante
repo_url: https://github.com/Requisitos-de-Software/2025.2-Grupo05
theme:

  name: material

  custom_dir: overrides

  logo: img/logo-jornada.png

  favicon: img/logo-jornada.png

  features:
    - navigation.tabs # abas no topo (padrão)
    - navigation.tabs.sticky # A aba fica fixa no topo ao rolar
    - navigation.top # Botão de "voltar ao topo" (padrão)
    - navigation.instant # navegação tipo SPA (Single Page App)
    - navigation.tracking # Atualiza a URL conforme você rola a página nos títulos
    - navigation.sections # Agrupa os itens da sidebar de forma mais limpa
    - navigation.expand # Abre a navegação lateral por padrão 
    - content.code.copy # Botão de copiar em blocos de código
    - content.action.edit
    - content.action.view

  font:
    text: Roboto # Padrão, mas limpa
    code: JetBrains Mono # Excelente para ler trechos de código/JSON/XML

  palette:
    # Modo Claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo # O azul 'indigo' costuma ser mais elegante que o 'blue' padrão
      accent: teal
      toggle:
        icon: material/weather-night
        name: Alternar para modo escuro

    # Modo Escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # O esquema 'slate' é um cinza azulado muito confortável
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Alternar para modo claro
plugins:
  - search
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slideEffect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Requisitos-de-Software/2025.2-Grupo05
      name: Repositório do Grupo

copyright: Copyright &copy; 2025 Jornada do Estudante - UnB

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed: # Permite abas dentro do conteúdo
      alternate_style: true 
  - pymdownx.highlight: # Cores no código
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true # Cria ícone de link ao lado dos títulos
  - md_in_html

nav:
  - Home: index.md
  - Sobre: Sobre/Sobre.md

  - Entregas:
      - Reuniões: Entregas/Reunioes.md
      - Inspeções:
          - Inspeções grupo 5:
              - Inspeção 1: Entregas/Inspeções/Inspeções_grupo5/Inspecao1.md
              - Inspeção 2: Entregas/Inspeções/Inspeções_grupo5/Inspecao2.md
              - Inspeção 3: Entregas/Inspeções/Inspeções_grupo5/Inspecao3.md
              - Inspeção 4: Entregas/Inspeções/Inspeções_grupo5/Inspecao4.md
              - Inspeção 5: Entregas/Inspeções/Inspeções_grupo5/Inspecao5.md
              - Inspeção 6: Entregas/Inspeções/Inspeções_grupo5/Inspecao6.md
          - Inspeções de outros grupos:
              - Inspeção 1 (GP6): Entregas/Inspeções/Inspeções_grupo6/Inspecao1.md
              - Inspeção 2 (GP6): Entregas/Inspeções/Inspeções_grupo6/Inspecao2.md
              - Inspeção 3 (GP6): Entregas/Inspeções/Inspeções_grupo6/Inspecao3.md
              - Inspeção 4 (GP6): Entregas/Inspeções/Inspeções_grupo6/Inspecao4.md
              - Inspeção 5 (GP1): Entregas/Inspeções/Inspeções_grupo6/Inspecao5.md
              - inspeção 6 (GP6): Entregas/Inspeções/Inspeções_grupo6/Inspecao6.md
      - Apresentações:
          - Apresentação 1: Entregas/Apresentações/Apresentacao1.md
          - Apresentação 2: Entregas/Apresentações/Apresentacao2.md
          - Apresentação 3: Entregas/Apresentações/Apresentacao3.md
          - Apresentação 4: Entregas/Apresentações/Apresentacao4.md
          - Apresentação 5: Entregas/Apresentações/Apresentacao5.md
          - Apresentação 6: Entregas/Apresentações/Apresentacao6.md
          - Apresentação final: Entregas/Apresentações/ApresentacaoFinal.md

  - Planejamento:
      - Metodologia: Planejamento/Metodologia.md
      - Ferramentas: Planejamento/Ferramentas.md
      - Aplicativo Selecionado:
          - Jornada do Estudante: Planejamento/Aplicativo_selecionado.md
          - Termo de uso: Planejamento/termo_de_uso.md
      - Aplicativos Analisados: Planejamento/Aplicativo_analisado.md
      - Cronograma: Planejamento/Cronograma.md
      - Heatmap: Planejamento/Heatmap.md
      - Validações da monitora: Planejamento/ValidacaoMonitora.md

  - Atas:
      - 1. Ata de Reunião(04/09): Atas/ata09-04.md
      - 2. Ata de Reunião(05/09): Atas/ata09-05.md
      - 3. Ata de Reunião(06/09): Atas/ata09-06.md
      - 4. Ata de Reunião(07/09): Atas/ata09-07_1.md
      - 5. Ata de Reunião(07/09): Atas/ata09-07_2.md
      - 6. Ata de Reunião(09/09): Atas/ata09-09.md
      - 7. Ata de Reunião(12/09): Atas/ata09-12.md
      - 8. Ata de Reunião(13/09): Atas/ata09-13_1.md
      - 9. Ata de Reunião(13/09): Atas/ata09-13_2.md
      - 10. Ata de Reunião(13/09): Atas/ata09-13_3.md
      - 11. Ata de Reunião(15/09): Atas/ata09-15.md
      - 12. Ata de Reunião(16/09): Atas/ata09-16.md
      - 13. Ata da Reunião(18/09): Atas/ata09-18.md
      - 14. Ata da Reunião(21/09): Atas/ata09-21.md
      - 15. Ata da Reunião(22/09): Atas/ata09-22.md
      - 16. Ata da Reunião(24/09): Atas/ata09-24.md
      - 17. Ata da Reunião(25/09): Atas/ata09-25_1.md
      - 18. Ata da Reunião(25/09): Atas/ata09-25_2.md
      - 19. Ata da Reunião(03/10): Atas/ata10-03.md
      - 20. Ata da Reunião(07/10): Atas/ata10-07.md
      - 21. Ata da Reunião(12/10): Atas/ata10-12_1.md
      - 22. Ata da Reunião(12/10): Atas/ata10-12_2.md
      - 23. Ata da Reunião(12/10): Atas/ata10-12_3.md
      - 24. Ata da Reunião(12/10): Atas/ata10-12_4.md
      - 25. Ata da Reunião(14/10): Atas/ata10-14.md
      - 26. Ata da Reunião(16/10): Atas/ata10-16.md
      - 27. Ata da Reunião(17/10): Atas/ata10-17.md
      - 28. Ata da Reunião(18/10): Atas/ata10-18.md
      - 29. Ata da Reunião(20/10): Atas/ata10-20.md
      - 30. Ata da Reunião(30/10): Atas/ata10-30.md
      - 31. Ata da Reunião(04/11): Atas/ata11-04.md
      - 32. Ata da Reunião(05/11): Atas/ata11-05.md
      - 33. Ata da Reunião(09/11): Atas/ata11-09.md
      - 34. Ata da Reunião(13/11): Atas/ata11-13.md

  - Pré-Rastreabilidade:
      - Rich Picture: Pré-Rastriabilidade/Rich-picture.md
      - Lista de verificação: Pré-Rastriabilidade/Rich_pictureLV.md

  - Elicitação:
      - Perfil de usuário: Elicitação/Perfil_usuario.md
      - Tecnicas:
          - Análise de documentação: Elicitação/Tecnicas/Analise_docs.md
          - Brainstorming: Elicitação/Tecnicas/Brainstorming.md
          - Entrevista: Elicitação/Tecnicas/Entrevista.md
          - Questionário: Elicitação/Tecnicas/Questionário.md
      - Requisitos Elicitados: Elicitação/Requisitos-Elicitados.md
      - Priorização:
          - Tree Level Scale: Elicitação/Priorização/Three_level_scale.md
          - In or Out: Elicitação/Priorização/In_or_Out.md
          - $100 dólares: Elicitação/Priorização/100_dolares.md
          - MoSCoW: Elicitação/Priorização/Moscow.md
      - Listas de verificação:
          - Elicitações:
              - Análise de documentação: Elicitação/LVs/elicitações/Lv_analise_docs.md
              - Entrevista: Elicitação/LVs/elicitações/Lv_entrevista.md
              - Questionário: Elicitação/LVs/elicitações/QuestionarioLV.md
              - Brainstorming: Elicitação/LVs/elicitações/BrainstormLV.md
          - Priorizações:
              - Three-level scale: Elicitação/LVs/priorizações/LV_Three_level.md
              - Moscow: Elicitação/LVs/priorizações/MoscowLV.md
              - 100 dólares: Elicitação/LVs/priorizações/100_dolaresLV.md
              - In or out: Elicitação/LVs/priorizações/In_or_outLV.md

  - Modelagem:
      - Cenários: Modelagem/Cenários.md
      - Léxicos: Modelagem/Léxicos.md
      - Casos de Uso: Modelagem/Casos-de-uso.md
      - Especificação: Modelagem/Especificacao.md
      - Ágil:
          - Histórias de usuário: Modelagem/Ágil/HistoriaUsuario.md
          - Backlog: Modelagem/Ágil/Backlog.md
          - NFR Framework: Modelagem/Ágil/NFR-Framework.md

      - Listas de Verificação:
          - Cenários: Modelagem/LVs/LVCenario.md
          - Léxico: Modelagem/LVs/LVLexico.md
          - Especificação suplementar: Modelagem/LVs/LVSuplementar.md
          - Caso de uso: Modelagem/LVs/LVUseCase.md
          - Ágil:
              - História de usuário: Modelagem/LVs/Ágil/HULV.md
              - Backlog: Modelagem/LVs/Ágil/BacklogLV.md
              - NFR Framework: Modelagem/LVs/Ágil/NFRLV.md
  - Análise:
      - Prototipação: Análise/Prototipacao.md
      - Comprovação informal: Análise/Comprovacao.md
      - Analise de Resultados: Análise/Analises.md

  - Pós-Rastreabilidade:
      - Forward-From: Pós-Rastreabilidade/Forward-From.md
      - Backward-From: Pós-Rastreabilidade/Backward-From.md
      - Matriz de Rastreabilidade: Pós-Rastreabilidade/Matriz_Rastreabilidade.md
      - Listas de verificação:
        - Elos de Rastreabilidade: Pós-Rastreabilidade/Lvs/Elos-Rastreabilidade.md

  - Entrega final:
      - Entrega final: EntregaFinal/final.md

  - Aplicativo Anterior:
      - Sobre: Aplicativo_anterior/Sobre_hbo.md
      - Rich Picture: Aplicativo_anterior/Rich_picture_hbo.md
      - Aplicativo Selecionado: Aplicativo_anterior/Aplicativo_selecionado_hbo.md